"use client";

import React from "react";
import { RecentsList } from "@/components/dashboard/RecentsList";
import { mapGenerationToRecentItem } from "@/lib/ai/mappers";
import { Sparkles } from "lucide-react";
import { PremiumLock } from "@/components/common/PremiumLock";

const DUMMY_ITEMS = [
    {
        title: "Advanced Calculus Summary",
        type: "Study Notes",
        meta: "Generated by Sarah J.",
        author: "Sarah J.",
        iconType: "note",
    },
    {
        title: "Organic Chemistry Flashcards",
        type: "Flashcards",
        meta: "Generated by Mike R.",
        author: "Mike R.",
        iconType: "question",
    },
    {
        title: "Macroeconomics Knowledge Tree",
        type: "Knowledge Tree",
        meta: "Generated by Alex K.",
        author: "Alex K.",
        iconType: "tree",
    },
];

export function ResourceGenerations({
    generations,
    isPremium = false,
}: {
    generations: unknown[];
    isPremium?: boolean;
}) {
    // If premium and no generations, don't show anything
    if (isPremium && (!generations || generations.length === 0)) return null;

    const items =
        isPremium || generations.length > 0
            ? generations.map((gen) =>
                  mapGenerationToRecentItem(
                      gen as any,
                      (gen as any).userName || "You"
                  )
              )
            : DUMMY_ITEMS;

    return (
        <div className="mt-12 relative">
            <div className="flex items-center justify-between mb-6">
                <h3 className="text-xl font-serif font-bold text-foreground flex items-center gap-2">
                    Community Generated Content
                    {!isPremium && (
                        <Sparkles className="w-4 h-4 text-primary animate-pulse" />
                    )}
                </h3>
            </div>

            <PremiumLock
                isPremium={isPremium}
                title="Unlock Community Insights"
                description="Join our premium community to access a large collection of AI-assisted study notes, flashcards, and knowledge trees contributed by the community."
            >
                <RecentsList
                    items={items as Parameters<typeof RecentsList>[0]["items"]}
                />
            </PremiumLock>
        </div>
    );
}
